apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: erzbir-higan-user-annotation-setting
spec:
  targetRef:
    group: ""
    kind: User
  formSchema:
    - $formkit: attachment
      name: 'erzbir.com/avatar'
      label: 作者页头图
